version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - ./firebase.json:/app/firebase.json
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: projetecolelaravel
      DB_USERNAME: soda
      DB_PASSWORD: soda1616
    depends_on:
      - postgres
    expose:
      - "9000"  # Expose PHP-FPM port

  webserver:  # Assurez-vous que le nom est bien "webserver"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: projetecolelaravel
      POSTGRES_USER: soda
      POSTGRES_PASSWORD: soda1616
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
