version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=projetecolelaravel
      - DB_USERNAME=soda
      - DB_PASSWORD=soda1616

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: projetecolelaravel
      POSTGRES_USER: soda
      POSTGRES_PASSWORD: soda1616
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
