version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www
      - /gestion-ecole/firebase.json:/home/sodadiop/Documents/beyond-fashion-api-ts/GestionEcole/gestion-ecole/docker-compose.yml
    ports:
      - "8000:8000"  # Le serveur Artisan écoutera sur ce port
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres  # Nom du service PostgreSQL
      DB_PORT: 5432
      DB_DATABASE: projetecolelaravel
      DB_USERNAME: soda
      DB_PASSWORD: soda1616

  postgres:  # Service PostgreSQL
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: projetecolelaravel
      POSTGRES_USER: soda
      POSTGRES_PASSWORD: soda1616
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:  # Volume persistant pour les données PostgreSQL