version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    environment:
      - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=pgsql
            - DB_HOST=pgsql
            - DB_PORT=db
            - DB_DATABASE=projetecolelaravel
            - DB_USERNAME=postgres
            - DB_PASSWORD=secret
            - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
            - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
            - MAIL_MAILER=${MAIL_MAILER}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
            - AUTH_DRIVER=${AUTH_DRIVER}
            - APP_PORT=${PORT}
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: projetecolelaravel
      POSTGRES_USER: soda
      POSTGRES_PASSWORD: soda1616
    ports:
      - "5434:5432"
    networks:
      - laravel_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  laravel_network:
    driver: bridge

volumes:
  postgres_data: {}